### ISSUE TITLE
[improvement request] Decompose package

### ISSUE THREAD

**Issue by sovaalexandr** [lucasvscn/snowflake#2]
It would be quite nice to be able to use [IdWorker](https://github.com/lucasvscn/snowflake/blob/master/src/Snowflake/IdWorker.php) without dependency on `illuminate/support` (which by itself requires extensions like `mbstring`) or any other.

**Comment by lucasvscn** [comment]
I agree with you. Snowflake no longer requires symfony or laravel components. Now you can upgrade for 0.3.0 ;)

**Comment by sovaalexandr** [comment]
Thanks a lot
